package com.game.risk.view;

import java.awt.Color;
import java.awt.Font;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import com.game.risk.model.Player;

/**
 *
 * @author cube
 */
public class PlayerPanel extends JPanel {

	/**
	 * JPanel object
	 */
	private JPanel statusPanel;

	private JFrame frame;

	private static final long serialVersionUID = 165014117961623530L;

	private List<Player> players;

	private JLabel statusLabel;

	int totalCountries;

	/**
	 * @param players
	 * @param playerList
	 * @param totalCountries
	 */
	public PlayerPanel(List<Player> players, int totalCountries) {
		this.players = players;
		this.totalCountries = totalCountries;
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		
		JPanel dominationPanel = new JPanel();
		dominationPanel.setBackground(Color.WHITE);
		dominationPanel.setBounds(0, 553, 782, 130);
		dominationPanel.setLayout(null);
		
		JLabel player = new JLabel("Player 1");
		player.setFont(new Font("Tahoma", Font.BOLD, 13));
		player.setForeground(Color.BLACK);
		player.setBounds(5, 13, 142, 30);
		dominationPanel.add(player);

		statusPanel = this;
		statusPanel.setBackground(Color.BLACK);
		statusPanel.setForeground(Color.BLACK);
		statusPanel.setName("statusPanel");
		statusPanel.setBorder(null);

		statusLabel = new JLabel();
		// statusLabel.setBounds(new Rectangle(x, y, width, height)); `zs
		statusLabel.setFont(new Font("Segoe UI", Font.BOLD, 20));
		statusLabel.setForeground(Color.WHITE);
		statusLabel.setName("statusLabel");
		statusPanel.add(statusLabel);

	}

	// @Override
	// public void paintComponent(Graphics g) {
	// super.paintComponent(g);
	// String name;
	// int playerIndex;
	// int playerNum;
	// int armies;
	// int pos = 0;
	// int w;
	// Font f = new Font("Arial", Font.BOLD, 26);
	//
	// for (int i = 0; i < players.size(); i++) {
	//
	// Player currentPlayer = players.get(i);
	// int countriesOwned = currentPlayer.getCountriesOwned().size();
	// double dominationPercentage = countriesOwned / totalCountries;
	//
	// w = 850 - (players.size() * 75);
	// pos = 125;
	// g.setFont(f);
	// g.setColor(Color.white);
	// g.drawString("Simon", pos, 40);
	//
	// // Assign th player color
	// if (i == 0)
	// g.setColor(Color.red);
	// if (i == 1)
	// g.setColor(Color.blue);
	// if (i == 2)
	// g.setColor(Color.yellow);
	// if (i == 3)
	// g.setColor(Color.green);
	// if (i == 4)
	// g.setColor(Color.pink);
	// if (i == 5)
	// g.setColor(Color.orange);
	//
	// g.fillRect(pos + (i * 75), 63, w, 20);
	//
	// }
	//
	// }
}
